version: "3.9"

name: elastic-lab
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: es01
    environment:
      discovery.type: single-node
      xpack.security.enabled: ${ELASTIC_SECURITY_ENABLED}
      xpack.security.http.ssl.enabled: ${ELASTIC_SECURITY_SSL}
      path.repo: /snapshots
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - essnapshots:/snapshots
    networks: [elastic]

  kib01:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kib01
    depends_on: [es01]
    environment:
      ELASTICSEARCH_HOSTS: "http://es01:9200"
    ports:
      - "5601:5601"
    networks: [elastic]

volumes:
  esdata:
    driver: local
  essnapshots:
    driver: local

networks:
  elastic:
    driver: bridge
