name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip docs
        run: zip -r docs.zip docs

      - name: Create GitHub release (auto notes)
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          fail_on_unmatched_files: false
          files: |
            kibana/saved_objects.ndjson
            docs.zip
